server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://zzanglog.cwint2ymszc7.ap-northeast-2.rds.amazonaws.com:3306/zzanglog
#    username: zxkim2004
#    password: 7595021zx

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: 1234

  session:
    store-type: none

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  profiles:
    include:

jwt:
  secret: zz123456789012345678901234567890
  token-valid-time: 86400

file:
  path: D:\project\zzanglog\upload\

ck:
  path: D:\project\zzanglog\ckImage\

#
#    oauth2:
#      client:
#        registration:
#          facebook:
#            client-id: 600275614291536
#            client-secret: 286a3327bd82177c3e1eb7d65865da1a
#            scope:
#            - public_profile
#            - email
#


